### ISSUE TITLE
REMAKE INTERFACE

### ISSUE THREAD

**Issue by eugeneloza** [eugeneloza/decoherence#158]
As bad as it could be, it is unavoidable to rewrite the interface from the scratch (hopefully, using as much as possible from the old one).

- [x] ~~Everything should inherit from DAbstractInterface (x1,y1,x2,y2,w,h,a) which would replace CurrentAnimationState.~~
- [x] No "content" and "frame" - they must be two distinctive Children of the DSingleInterfaceElement, with a simple procedure to create them.
- [x] All scaling must be done relative to ~~Parent~~ Anchors.
- [x] ~~Rescaling would be different for DSingleInterfaceElement and DInerfaceElement (as for each child). Thou one or two checks would be more than enough.~~
closes #155 
closes #9

**Comment by eugeneloza** [comment]
Also should fix #128

**Comment by eugeneloza** [comment]
Alignment relative to Parent (left/right/center, top/bottom/middle)
Anchors??? I don't want to make any anchors!

**Comment by eugeneloza** [comment]
Hmmm... Anchors might solve #8 
So... it looks like I don't have much choice...

**Comment by eugeneloza** [comment]
Anchor type atSlide (default), atScale
Adjust anchor after rescale

**Comment by eugeneloza** [comment]
This would look like
```
procedure Self.Rescale;
for i in Children i.Rescale;
procedure Self.AdjustAnchor
for i in Chidren i.AdjustAnchor;
```
doesn't look nice, but no better ideas yet. Maybe, `AdjustAnchor` may be used in `Rescale`. Thou it might yield artifacts during animations if the anchored object's `Rescale` is processed later than current `AdjustAnchor`.

**Comment by eugeneloza** [comment]
No parent-scaling. All should be done by `Anchor`.

**Comment by eugeneloza** [comment]
Make Txywha self-contained.

**Comment by eugeneloza** [comment]
Txywha as a child of DAbstractInterface?

**Comment by eugeneloza** [comment]
Simple procedure to Anchor a Child to Parent.

**Comment by eugeneloza** [comment]
`DFrameImage` as interface element, containing "content" with proper gaps and scaling

**Comment by eugeneloza** [comment]
A very eloquent demonstration on how inefficiently the interface works now: https://github.com/eugeneloza/decoherence/commit/4768a3d5c994a23bd693641937ad035be86f32ba (and actually even with this fix it works wrong). One can imagine how cool it'll be to work with a dozen or two of interface elements...
Thou it doesn't seem that it'll be too hard to remake everything. Only scaling and parenting routines will be changed significantly. So, I hope I'll be enough with one day for this issue... But as usually I'm underestimating the amount of work and overestimating my efficiency, I guess...

**Comment by eugeneloza** [comment]
Warning, some animations are scaled relative to Window, and some relative to Container. Should keep an eye on it until everything is working as expected.

**Comment by eugeneloza** [comment]
Looks like `DecoInterface.pas` is finished, unless something shows up while editing other units.
10 relatively inefficient hours out of 17 available today. Not as good as I'd want it, but much better than nothing :)

**Comment by eugeneloza** [comment]
Todo remaining:

- [ ] Images
- [ ] Labels
- [ ] GUI
- [ ] Composite
- [ ] Blocks
- [ ] Finalize

Thou there shouldn't be much change there, only carefully uncomment everything, keeping in mind all the changes to the core. There will still be a significant change in the layout coordinates, thou it also should be easy, thou will require a lot of attention.

**Comment by eugeneloza** [comment]
To think over: Maybe, move `Self.AbstractContainer` back to `Current.AbstractContainer`. It doesn't seem that it's required to keep current animation state in root, and it overcrowds the root a bit. Will also give a bit more order in `constructor`/`destructor`.

**Comment by eugeneloza** [comment]
A day wasted... I hate that feeling. Time's running short and so much to do left... :(

**Comment by eugeneloza** [comment]
GUI is ready. However, some functions still have be moved to Interface Elements (e.g. LoadScreenElement).

**Comment by eugeneloza** [comment]
Nearly made the same mistake again. The architecture bug seems to be fixed for good now. Still some scaling/position inconsistencies, but I hope they're not critical.

**Comment by eugeneloza** [comment]
Composite interface no longer needs `ArrangeChildren` at least in the way it worked before? Should `Children` be arranged on create or by a special procedure?

**Comment by eugeneloza** [comment]
Practically everything that's left is spread across specific issues. So, closing this one.
