### ISSUE TITLE
Battle mode

### ISSUE THREAD

**Issue by eugeneloza** [eugeneloza/decoherence#19]
GAME:
- [x] Time flow (partly done)
- [x] Soft pause (partly done)
- [ ] Hard pause (partly done)
- [x] Actor action
- [ ] enemy class
- [x] enemy AI

CONSTRUCTOR:
- [ ] manage enemy

**Comment by eugeneloza** [comment]
Subsequent tasks should be more specific.
