### ISSUE TITLE
Player Character

### ISSUE THREAD

**Issue by eugeneloza** [eugeneloza/decoherence#21]
GAME:

- [ ] Player character class (partly done)
- [ ] Race&profession (partly done)
- [ ] Issue commands (interface)

- [ ] Load Race
- [ ] Load Profession
- [ ] Load Avatar

CONSTRUCTOR

- [ ] Race
- [ ] Profession
- [ ] Avatars
