### ISSUE TITLE
Move context to Decoherence

### ISSUE THREAD

**Issue by eugeneloza** [eugeneloza/decoherence#39]
GAME

- [x] Move context unit
- [x] Update context unit (make context type variable)

CONSTRUCTOR

- [ ] Context event
- [ ] Create context element
- [ ] Create meta context list
- [ ] Assign context to event

**Comment by eugeneloza** [comment]
Let's close this one in favour of more specific issues, when `events` will be ready to work (and therefore technical requirements for context will become clear).
