### ISSUE TITLE
Send and catch events

### ISSUE THREAD

**Issue by eugeneloza** [eugeneloza/decoherence#45]
INTERFACE:

- [ ] Event displayer interface element
- [ ] Event types
- [ ] Send event
- [ ] Listen to events
- [ ] Attach sound to events
- [ ] Pause on events

GAME:

- [ ] Send events at game situations

**Comment by eugeneloza** [comment]
SendEvent(trigger: TTriggerID);
