### ISSUE TITLE
Voice Acting

### ISSUE THREAD

**Issue by eugeneloza** [eugeneloza/decoherence#46]
CONTENT
- [ ] Use Nikita's Voice acting
- [ ] Finalize the test scenario
- [ ] Record my Voice acting
- [ ] Process my Voice acting
- [ ] Cut my Voice acting
- [ ] Use my Voice acting

GAME
- [ ] Load Voice
- [ ] Attach Voice to actors
- [ ] Cut scenes

CONSTRUCTOR
- [ ] Phrase
- [ ] Phrase - sound link
- [ ] Triggers on events
