### ISSUE TITLE
Party.Camera or PlayerCamera

### ISSUE THREAD

**Issue by eugeneloza** [eugeneloza/decoherence#65]
- [x] Manual input handling
- [x] Manual camera management
- [x] Innertion movement
- [ ] Camera shake
- [ ] Camera cutscene animation

**Comment by eugeneloza** [comment]
https://github.com/eugeneloza/decoherence/commit/4c60159836bb49ce695d437b198cd2cd61d477f5

**Comment by eugeneloza** [comment]
https://github.com/eugeneloza/decoherence/commit/6bcfec7d9fe0ec1b2a8ca989113fdf977dcf54c7 and https://github.com/eugeneloza/decoherence/commit/053d5414e17e3ad7400c7604612c8b3c743559dc

**Comment by eugeneloza** [comment]
Everything needed here is implemented. Closing this one in favor to more specific issues.
